export const hobbiesRelacionamento = [
  "Filmes",
  "Séries",
  "Cinema",
  "Teatro",
  "Shows",
  "Concertos",
  "Música ao vivo",
  "Podcasts",
  "Animes",
  "K-dramas",
  "Documentários",
  "Jogos online",
  "Games de console",
  "Games mobile",
  "E-sports",
  "Programação",
  "Tecnologia",
  "Startups",
  "Inteligência Artificial",
  "Criação de conteúdo",
  "Streaming",
  "Academia",
  "Musculação",
  "Corrida",
  "Caminhada",
  "Crossfit",
  "Yoga",
  "Pilates",
  "Natação",
  "Ciclismo",
  "Artes marciais",
  "Futebol",
  "Vôlei",
  "Basquete",
  "Viajar",
  "Mochilão",
  "Praia",
  "Montanha",
  "Camping",
  "Ecoturismo",
  "Viagens internacionais",
  "Viagens de carro",
  "Fotografia de viagem",
  "Cozinhar",
  "Gastronomia",
  "Culinária internacional",
  "Comida vegana",
  "Comida vegetariana",
  "Churrasco",
  "Doces",
  "Leitura",
  "Livros",
  "Ficção",
  "Não-ficção",
  "Fantasia",
  "Autoajuda",
  "Psicologia",
  "Filosofia",
  "História",
  "Aprender idiomas",
  "Desenho",
  "Pintura",
  "Ilustração",
  "Fotografia",
  "Design",
  "Moda",
  "Artesanato",
  "Escrita criativa",
  "Poesia",
  "Produção musical",
  "Meditação",
  "Autoconhecimento",
  "Espiritualidade",
  "Mindfulness",
  "Vida saudável",
  "Minimalismo",
  "Sustentabilidade",
  "Voluntariado",
  "Cachorros",
  "Gatos",
  "Animais de estimação",
  "Adoção de pets",
  "Passear com pets",
  "Sair com amigos",
  "Festas",
  "Eventos sociais",
  "Networking",
  "Conhecer pessoas",
];
