/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _privateIndexRouteImport } from './routes/__private/index'
import { Route as _publicRegisterRouteImport } from './routes/__public/register'
import { Route as _publicPreloadRouteImport } from './routes/__public/preload'
import { Route as _publicLoginRouteImport } from './routes/__public/login'
import { Route as _publicCreate_personRouteImport } from './routes/__public/create_person'
import { Route as _privateMatchRouteImport } from './routes/__private/match'
import { Route as _privateCommentRouteImport } from './routes/__private/$comment'
import { Route as _privatePerfilIndexRouteImport } from './routes/__private/perfil/index'
import { Route as _privateContactIndexRouteImport } from './routes/__private/contact/index'
import { Route as _privatePerfilPerfilRouteImport } from './routes/__private/perfil/$perfil'
import { Route as _privateContactChatRouteImport } from './routes/__private/contact/$chat'

const _privateIndexRoute = _privateIndexRouteImport.update({
  id: '/__private/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicRegisterRoute = _publicRegisterRouteImport.update({
  id: '/__public/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicPreloadRoute = _publicPreloadRouteImport.update({
  id: '/__public/preload',
  path: '/preload',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicLoginRoute = _publicLoginRouteImport.update({
  id: '/__public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicCreate_personRoute = _publicCreate_personRouteImport.update({
  id: '/__public/create_person',
  path: '/create_person',
  getParentRoute: () => rootRouteImport,
} as any)
const _privateMatchRoute = _privateMatchRouteImport.update({
  id: '/__private/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const _privateCommentRoute = _privateCommentRouteImport.update({
  id: '/__private/$comment',
  path: '/$comment',
  getParentRoute: () => rootRouteImport,
} as any)
const _privatePerfilIndexRoute = _privatePerfilIndexRouteImport.update({
  id: '/__private/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const _privateContactIndexRoute = _privateContactIndexRouteImport.update({
  id: '/__private/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const _privatePerfilPerfilRoute = _privatePerfilPerfilRouteImport.update({
  id: '/__private/perfil/$perfil',
  path: '/perfil/$perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const _privateContactChatRoute = _privateContactChatRouteImport.update({
  id: '/__private/contact/$chat',
  path: '/contact/$chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$comment': typeof _privateCommentRoute
  '/match': typeof _privateMatchRoute
  '/create_person': typeof _publicCreate_personRoute
  '/login': typeof _publicLoginRoute
  '/preload': typeof _publicPreloadRoute
  '/register': typeof _publicRegisterRoute
  '/': typeof _privateIndexRoute
  '/contact/$chat': typeof _privateContactChatRoute
  '/perfil/$perfil': typeof _privatePerfilPerfilRoute
  '/contact/': typeof _privateContactIndexRoute
  '/perfil/': typeof _privatePerfilIndexRoute
}
export interface FileRoutesByTo {
  '/$comment': typeof _privateCommentRoute
  '/match': typeof _privateMatchRoute
  '/create_person': typeof _publicCreate_personRoute
  '/login': typeof _publicLoginRoute
  '/preload': typeof _publicPreloadRoute
  '/register': typeof _publicRegisterRoute
  '/': typeof _privateIndexRoute
  '/contact/$chat': typeof _privateContactChatRoute
  '/perfil/$perfil': typeof _privatePerfilPerfilRoute
  '/contact': typeof _privateContactIndexRoute
  '/perfil': typeof _privatePerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__private/$comment': typeof _privateCommentRoute
  '/__private/match': typeof _privateMatchRoute
  '/__public/create_person': typeof _publicCreate_personRoute
  '/__public/login': typeof _publicLoginRoute
  '/__public/preload': typeof _publicPreloadRoute
  '/__public/register': typeof _publicRegisterRoute
  '/__private/': typeof _privateIndexRoute
  '/__private/contact/$chat': typeof _privateContactChatRoute
  '/__private/perfil/$perfil': typeof _privatePerfilPerfilRoute
  '/__private/contact/': typeof _privateContactIndexRoute
  '/__private/perfil/': typeof _privatePerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$comment'
    | '/match'
    | '/create_person'
    | '/login'
    | '/preload'
    | '/register'
    | '/'
    | '/contact/$chat'
    | '/perfil/$perfil'
    | '/contact/'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$comment'
    | '/match'
    | '/create_person'
    | '/login'
    | '/preload'
    | '/register'
    | '/'
    | '/contact/$chat'
    | '/perfil/$perfil'
    | '/contact'
    | '/perfil'
  id:
    | '__root__'
    | '/__private/$comment'
    | '/__private/match'
    | '/__public/create_person'
    | '/__public/login'
    | '/__public/preload'
    | '/__public/register'
    | '/__private/'
    | '/__private/contact/$chat'
    | '/__private/perfil/$perfil'
    | '/__private/contact/'
    | '/__private/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _privateCommentRoute: typeof _privateCommentRoute
  _privateMatchRoute: typeof _privateMatchRoute
  _publicCreate_personRoute: typeof _publicCreate_personRoute
  _publicLoginRoute: typeof _publicLoginRoute
  _publicPreloadRoute: typeof _publicPreloadRoute
  _publicRegisterRoute: typeof _publicRegisterRoute
  _privateIndexRoute: typeof _privateIndexRoute
  _privateContactChatRoute: typeof _privateContactChatRoute
  _privatePerfilPerfilRoute: typeof _privatePerfilPerfilRoute
  _privateContactIndexRoute: typeof _privateContactIndexRoute
  _privatePerfilIndexRoute: typeof _privatePerfilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__private/': {
      id: '/__private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _privateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public/register': {
      id: '/__public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof _publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public/preload': {
      id: '/__public/preload'
      path: '/preload'
      fullPath: '/preload'
      preLoaderRoute: typeof _publicPreloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public/login': {
      id: '/__public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public/create_person': {
      id: '/__public/create_person'
      path: '/create_person'
      fullPath: '/create_person'
      preLoaderRoute: typeof _publicCreate_personRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__private/match': {
      id: '/__private/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof _privateMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__private/$comment': {
      id: '/__private/$comment'
      path: '/$comment'
      fullPath: '/$comment'
      preLoaderRoute: typeof _privateCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__private/perfil/': {
      id: '/__private/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof _privatePerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__private/contact/': {
      id: '/__private/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof _privateContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__private/perfil/$perfil': {
      id: '/__private/perfil/$perfil'
      path: '/perfil/$perfil'
      fullPath: '/perfil/$perfil'
      preLoaderRoute: typeof _privatePerfilPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__private/contact/$chat': {
      id: '/__private/contact/$chat'
      path: '/contact/$chat'
      fullPath: '/contact/$chat'
      preLoaderRoute: typeof _privateContactChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  _privateCommentRoute: _privateCommentRoute,
  _privateMatchRoute: _privateMatchRoute,
  _publicCreate_personRoute: _publicCreate_personRoute,
  _publicLoginRoute: _publicLoginRoute,
  _publicPreloadRoute: _publicPreloadRoute,
  _publicRegisterRoute: _publicRegisterRoute,
  _privateIndexRoute: _privateIndexRoute,
  _privateContactChatRoute: _privateContactChatRoute,
  _privatePerfilPerfilRoute: _privatePerfilPerfilRoute,
  _privateContactIndexRoute: _privateContactIndexRoute,
  _privatePerfilIndexRoute: _privatePerfilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
